### ISSUE TITLE
Does not work with <style> @import url("..."); </style>

### ISSUE THREAD

**Issue by skh-** [BrowserSync/browser-sync#10]
This is a great tool.  However, it would be even better if it supported `@import`'s of stylesheets.

I realize that including stylesheets this way is not optimal, but it does get around IE's limitation of 31 stylesheets, and is useful when in development - particularly with CMS's that include a lot of stylesheets.

When I downloaded this tool to try it out I was working on a Drupal project, which happens to do this until you turn on CSS aggregation.  But at that point it also changes the name of the CSS files and caches them.

I took a look at modifying browser-sync-client.js but it seems like it's really only setup for altering `<link>` elements and ran short on time.

Thanks!

**Comment by jtomaszewski** [comment]
You could leave that open though. If not a but, definitely it's a missing feature not noted in README :<

Livereload has support not only for reloading @import url(*.css) stylesheets, but evne also for images f.e. `background-image:url()`. We can see how it's done f.e. here: https://github.com/livereload/livereload-js/blob/master/src/reloader.coffee#L182-L198 .

We could extend `codeSync.reload()` function (https://github.com/shakyShane/browser-sync-client/blob/master/lib/code-sync.js#L117-L151); but because of performance propably we shouldn't parse all the stylesheets (in order to look for `@import` tags) in .reload() function, but better have those references cached somewhere. What do you think?

**Comment by lasseyls** [comment]
+1 for this!

**Comment by lasseyls** [comment]
Or at least at it to the readme :-)

**Comment by Fidelix** [comment]
Should this really be closed? It would be a great feature!

**Comment by SgtPooki** [comment]
browser-sync start --server "." --files "**/*.*" --no-inject-changes

works perfectly for me.

**Comment by shakyShane** [comment]
@Fidelix - we are looking to add this feature in the future, yes.

@SgtPooki - that command cause a full reload per file-change, but this thread is actually about getting @import statements to cause CSS injection :)

**Comment by SgtPooki** [comment]
@shakyShane I didn't see the OP say anything about only wanting CSS injection, my bad. I figured others could benefit from some kind of working solution.

**Comment by shakyShane** [comment]
@SgtPooki - oh yeah, that's correct :)

Well either way, we'll be adding this In a way that allows css injection :)

**Comment by tanc** [comment]
Adding a note in the readme would have saved me hours of frustration. Although I should have just searched this issue queue to find this. Anyway, just a note in the readme as a starting point would really help new users (especially Drupal users) getting to grips with browser-sync.

**Comment by ryentzer** [comment]
+1 on adding to readme. Would have save a lot of time on my end. Thanks. :)

**Comment by gijsroge** [comment]
Place this in your template.php and it will generate link tags instead of @import's in your local environment.

```/**
   * Generate link tags instead of @import
   */
  $environment = variable_get('environment');
  if ($environment == 'development') {
    // Alter css to display as link tags.
    foreach ($css as $key => $value) {
      $css[$key]['preprocess'] = FALSE;
    }
  }```

**Comment by skh-** [comment]
I have been using a similar one as mentioned by @gijsroge.  Only difference is disabling `@import` based on the CSS aggregation setting (rather than the `environment` variable which isn't part of core).

```php
/**
 * Implements hook_css_alter().
 *
 * Disables @import CSS tags for compatibility with BrowserSync.
 */
function HOOK_css_alter(&$css) {

  // Aggregation must be disabled.
  if (!variable_get('preprocess_css')) {

    // Disable @import on each css file.
    foreach ($css as &$item) {

      // Compatibility with disabling stylesheets in theme.info (263967).
      if (file_exists($item['data'])) {
        $item['preprocess'] = FALSE;
      }
    }
  }
}
```

**Comment by dak** [comment]
I just ran into this issue earlier and a full page reload was not working in Safari, even with `Disable Cache` selected (manually flushing the cache did work, but is annoying), although it did work properly in Chrome with the cache disabled.

Interestingly though, this issue only exists with CSS (possibly Safari being a bit over enthusiastic at caching CSS), although requiring reloads instead of properly injecting can be annoying as well.

With HTTP/2, scoped styles, and the Shadow DOM, there are a number of cases where `@import` becomes far more useful than link injecting CSS.

It would be nice if this issue could get a bit higher priority for attention.

**Comment by iliakan** [comment]
You probably could port the code for reloading `url()`  and `import` from the chrome extension https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei

File `livereload.js`, see `Reloader.prototype.reloadStyleImages`, `Reloader.prototype.reloadStylesheet` and few other `reload*` methods.

**Comment by taivu** [comment]
similar to @skh-'s temp fix , but for Drupal 8:

```
/**
 * Implements hook_css_alter().
 *
 * Disables @import CSS tags for compatibility with BrowserSync CSS injection while developing.
 */
function YOURTHEMENAME_css_alter(&$css) {

  // get value from settings/local.settings
  $is_css_preprocess = \Drupal::config('system.performance')->get('css')['preprocess'];

  // Aggregation must be disabled.
  if (!$is_css_preprocess) {

    // Disable @import on each css file.
    foreach ($css as &$item) {

      // Compatibility with disabling stylesheets in theme.info (263967).
      if (file_exists($item['data'])) {
        $item['preprocess'] = FALSE;
      }
    }
  }
}
```

**Comment by pepelsbey** [comment]
Here’s my use case: I have `screen.css` with a number of imports:

```
@import 'defaults.css';
@import 'fonts.css';
…
```

There are more nested imports in some files. And I don’t process my styles with anything to complie a single file, I just don’t need to. What I need is BS to watch files and push changes to browser. But only changes in `screen.css` propagate to browser. Changes in imported files detected too, but BS don’t push them.

That’s how I start watcher:

```
browser-sync start --server --no-notify --no-ui --files 'index.html, styles/**'
```

Is it even possible to properly push changes from imported files? Is there a workaround for that, apart from reloading the whole page? Thank you.

**Comment by alvinpascoe** [comment]
Thanks @taivu. I wrapped mine in a custom module, but it works great!
