### ISSUE TITLE
Jekll, C9, JSON live reload problems 

### ISSUE THREAD

**Issue by alidcastano** [BrowserSync/browser-sync#1166]
I can't get browser-sync to refresh the page with Jekyll and JSON using terminal in C9 IDE.

### Versions

- Node v4.4.5
- npm v2.15.5
- Browsersync v2.14.0

### My setup 

As instructed, I put the browser-sync script in my HTML file before the ending of the </body> 

```
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:8080/browser-sync/browser-sync-client.2.14.0.js'><\/script>".replace("HOST", location.hostname));
//]]></script>

```
Then in my package.json file I created the following two scripts: 

 ```
 "scripts": {
    "jekyll": "jekyll serve --host $IP --port 8080",
    "sync": "browser-sync start --proxy https://mylocaldev.c9users.io --port 8080 --files _posts/*.md"
  }

```

Finally, I run `npm run jekyll` and then` npm run sync `

I get the following output: 

[BS] Proxying: https://mylocaldev.c9users.io
[BS] Access URLs:
 --------------------------------------
       Local: https://localhost:8081
    External: https://172.17.36.34:8081
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://172.17.36.34:3001
 --------------------------------------
[BS] Watching files...

 The changes are being logged, but the page is not being updated automatically. And the local access url says there is a proxy error. 

Not exactly sure how poxy works. Is the --port supposed to be the same one I am running Jekyll on? I've played around with different configurations but can't get this to run properly. What am I doing wrong? 

Thanks.

**Comment by joemaller** [comment]
There's nothing wrong with Browsersync, your `package.json` commands just need a few tweaks. 

The two following should be all you need to start Jekyll, and then proxy Jekyll's local url with BrowserSync. 

```json
"jekyll": "jekyll serve",
"sync": "browser-sync start --proxy 127.0.0.1:4000 --files _site/**/*"
```

With just `jekyll serve`, Jekyll opens a basic server at `127.0.0.1:4000`. Since you're going to proxy that with Browsersync, the default address is good enough. Don't bother watching the `_posts` directory either, Jekyll will take care of that. All Browsersync needs to care about are the output files in `_site`. Watching the output also captures compiled CSS files so Browsersync can inject them without a full page refresh.

Browsersync's `--port` argument specifies the port Browsersync will serve from. It defaults to 3000, but you can change it if you need to. 

One other thing, you don't need to add the `__bs_script__` snippet to your html files. Browsersync will inject the necessary snippets when proxying.

This issue would make a great Stack Overflow question.

**Comment by shakyShane** [comment]
@alidcastano can you please try the solution from @joemaller and let us know how you get on :)

**Comment by alidcastano** [comment]
Sorry, I created this issue was a while back and I'm not using C9 editor anymore. I'm pretty sure, however, that if you're using C9 you need to specify the $IP and $PORT to serve jekyll.

Other than that, I'm now using a similar script to run jekyll and browser-sync locally and it works like a charm. Thanks for following up.
