### ISSUE TITLE
Proxying an HTTPS server as HTTP

### ISSUE THREAD

**Issue by flodiebold** [BrowserSync/browser-sync#1590]
### Issue details

I'd like to proxy to an https server, but serve via http.

### Steps to reproduce/test case

E.g.
```
bs.init({
  proxy: { target: "https://some.page" },
  https: false
});
```
still serves the proxy via https, and there doesn't seem to be any way of overriding the automatic https.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.24.6  ]
- Node        [ 10.3.0   ]
- Npm         [  6.1.0  ]

### Affected platforms

- [ ] all

### Browsersync use-case

- [ ] all

**Comment by shakyShane** [comment]
@flodiebold can you explain your reasoning for this? I don't think it can be done since the choice internally to use http/https is based very much on the target, rather than the desired address to view locally.

I'm going to close as 'out of scope' - but if someone wants to contribute this feature, I'd be happy to hear about it :)
