### ISSUE TITLE
Allow serving one file for all urls (single page app mode)

### ISSUE THREAD

**Issue by wiemann** [BrowserSync/browser-sync#204]
Hi,
as many developers nowadays use Backbone, AngularJS etc. to build single page applications that consist of e.g. a /index.html page + pushstate routing, it would be great to have an option to make browser-sync serve one file. ("404/catchall/fallback" page you might also call it).

Maybe an option called {cachall: "/filename.html"} ?

**Comment by kosz** [comment]
not all apps need to be single page ... 
what if i have an app with an admin module, and i want the admin module to have it's own index.html ... 

having the ability to create routes would be nice. the suggested plugin blindly redirects to index.html .

**Comment by DarrylD** [comment]
@adamalbrecht you're the man for that tip! Works perfectly.

**Comment by scoarescoare** [comment]
Thank you! :thumbsup:

**Comment by cjmyles** [comment]
I've forked the [connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback) library and added some features to enable you to change the default index file, as well as provide rewrite patterns for specific urls. You can use this instead of the 'index' browsersync option which won't work when using the connect-history-api-fallback.

New library: [connect-history-middleware](https://github.com/cjmyles/connect-history-middleware)

**Comment by tombh** [comment]
@adamalbrecht's example needs to be updated to reference a function call rather than a variable;

```js
historyApiFallback = require('connect-history-api-fallback')

server: {
  baseDir: "...",
  middleware: [ historyApiFallback() ]
}
```

**Comment by silvenon** [comment]
Yep, no need for an additional feature since this is ridiculously easy to implement with either of those modules.

**Comment by jamespack** [comment]
@adamalbrecht worked perfectly and IMHO the easiest solution.

**Comment by tadams88** [comment]
@tombh edit was necessary for me (function call)

**Comment by shakyShane** [comment]
updated the example @adamalbrecht with the fix from @tombh

**Comment by darlanmendonca** [comment]
Thank you! :thumbsup:

**Comment by thunderkid** [comment]
For me the @adamalbrecht solution (with the @tombh edit) only works for urls that are one level deep. ie ```localhost:8080/atlantic``` works fine, but ```localhost:8080/france/paris``` gives a GET error again. Does anyone have a solution that works for >1 level?

**Comment by jgatjens** [comment]
@thunderkid works perfect for me with these ur
`http://localhost:3000/think/detail/why-sound-design-is-the-next-great-digital-frontier`
`http://localhost:3000/story/conor-brady`
`http://localhost:3000/office/calgary/map/main/-1/`

:+1:

**Comment by lukejacksonn** [comment]
Does anyone know if if there is a CLI equivalent to `middleware: [ historyApiFallback() ]`.. I have been using this in my gulp task and it works great but recently I've been trying to take advantage of npm scripts and can't figure out if this configuration can be achieved through the command line.

I'm thinking something along the lines of:
`browser-sync start --server dist --middleware historyApiFallback`
or if historyApiFallback was supported by browser-sync out of the box..
`browser-sync start --app dist`

**Comment by shakyShane** [comment]
@lukejacksonn just create a file called `bs.js` like


```js
var browserSync = require("browser-sync").create();

browserSync.init({
    files: ["app/css/*.css"],
    server: {
        baseDir: "app",
        middleware: [ historyApiFallback() ]
    }
});
```

then in your npm script, just do `"serve": "node bs.js"

**Comment by lukejacksonn** [comment]
@shakyShane that worked, thanks. It would be awesome to see this built in and exposed through the CLI. I'm going to fork and have a play around this weekend!

**Comment by Sukram21** [comment]
@thunderkid I had the same problem as you (worked only for urls that are one level deep) and solved it by adding ``<base href="/">`` to ``head`` in my index.html. 

I discovered this solution on https://www.bountysource.com/issues/22575141-404-not-found-if-hashbang-false

**Comment by mismith** [comment]
Is there no better option for CLI usage than deferring all your config to an external .js file? That seems like a pretty string argument to bring this functionality into core...

**Comment by dnutels** [comment]
@mismith 

Yeah... I am failing to understand that as well. 

I, personally, am partial to `--app` flag @lukejacksonn suggested.

**Comment by lassounski** [comment]
You could use [connect-modrewrite](https://github.com/tinganho/connect-modrewrite) to solve this.
In your Browserify configuration, require the connect-browserify module, and use it in the middleware option.

```
var modRewrite  = require('connect-modrewrite');

gulp.task('serve', function () {
    browserSync.init(null, {
        server: {
            baseDir: [APP_PATH],
            middleware: [
                modRewrite([
                    '!\\.\\w+$ /index.html [L]'
                ])
            ]
        }
    });

   // watch only for app specific codes;
   ...
});
```

**Comment by jesusoterogomez** [comment]
I have been experiencing the same error as @thunderkid, with `> 1` depth urls.

It actually works okay if I navigate to the links using the application's `a` tags. But reloading on the page itself, breaks the GET requests to assets again.

For example:

1. Application starts at `/`, link to `/test/1` is clicked. Everything works fine, css/js assets are loaded from '/`.

2. Application starts at `/`. I change the URL to  `/test/1` manually (or by window.location.href/assign). Assets are attempted to load relatively from `/test`, making all of them return `404`. Same thing happens if I set `startPath` to `/test/1` to make the app start at that specific route.

@jgatjens Do you have a different configuration that the one stated above?

**Comment by powerbuoy** [comment]
`historyApiFallback` worked flawlessly for me. _Until_ I tried to do a `gulp export`. For some reason I get the following error now:

    [13:12:37] 'export-normalized-resources' errored after 1.75 ms
    [13:12:37] TypeError: Install of %connect-history-api-fallback% to `^1.2.0` has no registry property provided.

I don't know enough about the build scripts, SystemJS etc to understand what's happening here at all so hoping for some insights.

Fwiw I installed it using `npm install --save-dev historyApiFallback` if that makes a difference.

**Comment by antonsamper** [comment]
I'm having the same as @thunderkid and @jesusoterogomez and unfortunately i cant use the `<base href="/">` trick that @Sukram21 suggested as I'm using using local SVGs and referencing them through the `<use></use>` tag. Adding the `<base href="/">` breaks my SVG references

**Comment by Sukram21** [comment]
@antonsamper Probably related: https://github.com/angular/angular.js/issues/8934 
This gist (https://gist.github.com/leonderijke/c5cf7c5b2e424c0061d2) should fix the problem for Firefox, its comments still mention problems with Chrome.

**Comment by antonsamper** [comment]
@Sukram21 yes definitely related, i came across that a few days ago. It's a shame the the polyfill doesnt work on Chrome

**Comment by danukhan** [comment]
@thunderkid 
@jgatjens 
I am also having the same issue where using historyApiFallback() is only working for one level. Did you get this issue resolved? Would love to see the solution.

**Comment by jgatjens** [comment]
@danukhan I remember it was working for all the levels with `adamalbrecht` solution

**Comment by danukhan** [comment]
@jgatjens The issue was that the resource urls (js and css) weren't correctly setup. The following post led me to the answer: http://stackoverflow.com/questions/10865480/mod-rewrite-to-index-html-breaks-relative-paths-for-deep-urls

Basically rather than having my resources as src="res/abc.js", I needed a leading slash like this: src="/res/abc.js"

**Comment by danukhan** [comment]
@jgatjens I'm facing same issue as originally mentioned here while deploying my app in tomcat. i.e., When I type localhost:8080/myapp/page1, I get 404 message. I would like to redirect it to localhost:8080/myapp/index.html as the solution for browserSynch. Do you know how can I do this for tomcat?

**Comment by jgatjens** [comment]
@danukhan you probably want to use http://tuckey.org/urlrewrite/. In my case, I used the htaccess redirects in prod.

**Comment by goldnetonline** [comment]
@lucasmotta come here dude, you need a wottle of bine. Thanks

**Comment by vpezeshkian** [comment]
Did you add a option for this yet? I don't feel like installing an entire module to achieve this, any suggestion?

**Comment by velkumars** [comment]
Hi, 

I have used gulp to build my client angularJS application. After i deployed into IIS i'm getting an issue. My page is working fine when navigate through menu's. But when i refresh by page (or) copy and paste the URL its giving me 404 error.
HTTP Error 404.0 - Not Found
can anyone help me, to resolved this?

**Comment by darlanmendonca** [comment]
@velkumars you problably are with html5 mode enabled, so you need configure your server to redirect all requests to your index.html

look here, has IIS configuration
http://stackoverflow.com/questions/12614072/how-do-i-configure-iis-for-url-rewriting-an-angularjs-application-in-html5-mode

other option, if you cant configure the server, is disable html5 mode, and use a hash in paths, but is a old way :D

**Comment by velkumars** [comment]
@darlanmendonca, thank you. i did the same way

**Comment by parth-BSP** [comment]
@lucasmotta - this was work like charm in my case..great thank you..
`var defaultFile = "index.html";

// I had to resolve to the previous folder, because this task lives inside a ./tasks folder
// If that's not your case, just use `__dirname`
var folder = path.resolve(__dirname, "./");
gulp.task('browser-sync', function() {
	browserSync.init({
	  open: true,
	  port: 80,
	  server: {
		baseDir: "./",
          middleware: function(req, res, next) {
              var fileName = url.parse(req.url);
              fileName = fileName.href.split(fileName.search).join("");
              var fileExists = fs.existsSync(folder + fileName);
              if (!fileExists && fileName.indexOf("browser-sync-client") < 0) {
                  req.url = "/" + defaultFile;
              }
              return next();
          }
		
	  }
	});`

**Comment by Mobe91** [comment]
I discovered that the [suggested middleware script](https://github.com/BrowserSync/browser-sync/issues/204#issuecomment-51469022) has an issue when the url path contains `null` as in `aurelia-templating-resources/null-repeat-strategy.js`. The `null` parts get dropped if `fileName.search == null`.

Here is an improved version that worked better for me:
```js
function(req, res, next) {
  var fileName = url.parse(req.url).pathname;
  var fileExists = fs.existsSync(folder + fileName);
  if (!fileExists && fileName.indexOf("browser-sync-client") < 0) {
    req.url = "/" + defaultFile;
  }
  return next();
}
```

**Comment by hieutranagi47** [comment]
I applied lucasmotta's solution and I could solve my case, but I'm facing another issue with "routes" option:
```
var defaultFile = 'index.html';
var folder = path.resolve(__dirname, './app');
var bowerFolder = path.resolve(__dirname, './bower_components');
browserSync.init({
    open: true,
    port: 8080,
    notify: false,
    minify: false,
    server: {
        baseDir: 'app',
        middleware: function(req, res, next) {
            var fileName = url.parse(req.url);
            fileName = fileName.href.split(fileName.search).join('');
            var fileExists = fs.existsSync(folder + fileName) || fs.existsSync(bowerFolder + fileName);
            if (!fileExists && fileName.indexOf('browser-sync-client') < 0) {
                req.url = '/' + defaultFile;
            }
            return next();
        },
        routes: {
            '/bower_components': 'bower_components'
        }
    }
});
```
I would like to inject all bower_components into index file to check some configurations in bower.json file for debug instead of merging them into a vendor.js file same as gulp build, and I don't want to store bower_components in app folder, so that, I would like to route bower_components to BrowserSync. but I don't why I can not load the bower file with routes option when I use lucasmotta's middleware.

**Comment by rhernandog** [comment]
Hello,

I'm facing a problem when implementing either @lucasmotta or @Mobe91  solutions using React Router and Webpack for deeper routes. Specifically for a route like this: `localhost:3000/first/second`.

When the browser is refreshed in that route (for code changes or manual refresh) I get the following console errors:
```
Uncaught SyntaxError: Unexpected token <       manifest.5d6f40b0a76d91d7d841.js:1 
Uncaught SyntaxError: Unexpected token <       vendor.53f4ed0e2a8504e5be36.js:1 
Uncaught SyntaxError: Unexpected token <       app.a815826d5053654ce308.js:1
```

The browser is actually finding the files, but the issue is that those files are actually the `index.html` file, so basically javascript is complaining about the less than sign of the opening `doctype` declaration: `<!doctype html>`, which is on the first line of the file.

I can actually go to every route in the app, regardless of the url (for example there's no issue when I use a `<Link />`  to go to `/first/second/third`), the problem is on reload, the request for each file that returns false is the `index.html` file.

Using the history api fallback doesn't work neither, in fact it doesn't even get the right url.

This is an example of how the request looks on reload: `/lists/js/app.a815826d5053654ce308.js`

I'll try with some regular expression to try to get rid of everything that comes before `/js` and `/css` and send that request, since normal naivagtion doesn't return false in the `fileExists` var.

But if someone has some more generic solution (mine would work only for my specific case) it'd be great!!.

**Comment by rhernandog** [comment]
Hello again,

I found a solution but just for my particular case, but it shouldn't be too hard for everyone to create their own though. Just some regular expressions and it works.

In my specific case I have my compiled files in the `/build` folder, so that modification has to be made in the folder var:
```javascript
var folder = path.resolve(__dirname, "./build");
```
Then, since the issue happens when reloading in a subfolder I created some code to check for more than one forward slash and to see if the request is a file with `/css` or `/js` in the filename.
```javascript
middleware: function (req, res, next) {
  var fileName = url.parse(req.url).pathname;
  var fileExists = fs.existsSync( folder + fileName );
  // test the file name for a .ico file
  var faviconTest = fileName.match( /\/favicon\.ico/g );
  // test the file name for sub-folders
  var subfolderTest = fileName.match( /\//g );
  // test to check if the requested url is a file or not
  var isCssJsFile = fileName.match(/\/css|\/js/g);

  if ( !fileExists && fileName.indexOf("browser-sync-client") < 0 && !faviconTest ) {
    // if the we're in a subfolder and the request is a file (JS|CSS)
    // create a new filename without anything previous to the file folder
    if ( subfolderTest && isCssJsFile ) {
      // create a new file name using the file type
      var newNameRegEx = new RegExp( isCssJsFile[0] + "(.+)", "g" );
      // request the new filename
      var newFileName = fileName.match( newNameRegEx )[0];
      req.url = newFileName;
    } else {
      // we're requesting the base folder so we need the regular index file
      req.url = "/" + defaultFile;
    }
  }
  return next();
}
```
The code just checks if the folders are there. If you have a different folder structure the code should adapt to that.

Is working fine so far on windows. Finally keep in mind that if you're requesting other files, those folder should also be included. An image's source included directly in the `<img>` tag doesn't have any trouble.

Best,
Rodrigo.

**Comment by sanof3322** [comment]
I've tried Rodrigo's solution with tricking req.url.  Even though browser shows no problem,  js/css/image files come empty. This is my implementation. 

Project file structure:
```
/app
   index.html
   app.js
   style.css
   libs.js
   /img
      favicon.ico
      site.webmanifest
      favicon-16x16.png
```

Browsersync init:
```
const browserSync = require("browser-sync").create();
const url = require('url');
let fs = require("fs");
const path = require("path");
const content_404 = fs.readFileSync(path.join(__dirname, './app/index.html'));
var folder = path.resolve(__dirname, "./app");

const serve = () => {
    browserSync.init({
        logLevel: "silent", //to disable browserSync snippet message
        server: {
            baseDir: "./app",
        },
    },
        (err, bs) => {
            bs.addMiddleware("*", (req, res) => {
                // Provides the 404 content without redirect.

                let fileName = url.parse(req.url).pathname;
                const fileNameArr = fileName.split("/");                
                fileName = fileNameArr[fileNameArr.length - 1];
                const filePath = `${folder}\\${fileName}`;
                const isCssJsFile = fileName.match(/css|js/g);
                const isFavicon = fileName.match(/png|ico|webmanifest/g);
                
                if(isCssJsFile){
                    res.write(fs.readFileSync(path.join(__dirname, `./app/${fileName}`)))
                }else if(isFavicon){
                    req.url = `./app/img/${fileName}`
                    res.write(fs.readFileSync(path.join(__dirname, `./app/img/${fileName}`)))
                }else {
                    res.write(content_404);
                }
                
                res.end();
            });
        }
    );
    
    //watchers go here
}

```

**Comment by Dynamics-crm-finery** [comment]
@miickel https://opencodes.space/questions/access-the-configuration-of-a-web-browser
