### ISSUE TITLE
Sync scroll  of scrollable div

### ISSUE THREAD

**Issue by mtscout6** [BrowserSync/browser-sync#273]
I have a site with a header and footer in fixed positions on the page. The main content then has an overflow hidden flag, thus the div itself is scrollable. Browser-Sync does not appear to be syncing that scroll behavior. Do I need to do anything to get that to work?

**Comment by looeee** [comment]
I'm really glad I found this plugin, it's taken me several hours of searching to find it though.

What's the reason for only supporting this as a plugin? It seems like it should be in the core. The `scrollElements` option allows you to sync scroll for any element, but then this scroll position is lost on refresh.

**Comment by looeee** [comment]
On further testing, I cannot get this to work. Neither the version outlined here nor [this one](https://gist.github.com/villelahdenvuo/b35768ba4daec99843e0c5cbab1885c5). 

I'm running browser sync using the script: 

``` js
"browser-sync": "browser-sync start -c .\\utility\\bs-config.cjs", 
```

Then in `bs-config.cjs` I have this:

``` 
module.exports = {
   ...
  plugin: function (opts, bs) {},
  hooks: {
    'client:events': function () {
      return ['div:scroll'];
    },
    'client:js': require('fs').readFileSync(
      './utility/bs-plugin/browsersync-scroll-plugin.cjs',
    ),
   ...
}
```

`browsersync-scroll-plugin.cjs` is exactly as described above except (my scroll elem is also `.scroller`). Everything works except that scroll position is lost on refresh. 

This issue is rather old now - should the code described here still work with the latest version of Browsersync?
