### ISSUE TITLE
Does not reload the proper html file

### ISSUE THREAD

**Issue by fbm-static** [BrowserSync/browser-sync#387]
For example, my browser is at `localhost:3000/single.html`. Then I make changes to index.html:`

```
[BS] File changed: /index.html
```

However, my page still gets reloaded even if i'm not at `/index.html`

**Comment by shakyShane** [comment]
Hi! 

There's currently no relationship between the file that changed on disk and which page is reloaded. As you've noticed, when you watch *all* `html` files, changing any of them will cause a full reload. This makes sense when you consider the file you've just edited might be a partial and therefore cannot ever be mapped to a URL in the browser...

So this is not actually a bug, it's expected behaviour. But it does highlight the potential for a direct mapping between files/urls - if we did that though, it would be behind an option wall

**Comment by shakyShane** [comment]
Closing as this is not actually a bug in BrowserSync itself.

**Comment by fbm-static** [comment]
> So this is not actually a bug, it's expected behaviour. But it does highlight the potential for a direct mapping between files/urls - if we did that though, it would be behind an option wall

Could this feature be added in the near future? I love you.
