### ISSUE TITLE
Click syncing causes phantom clicks on single browser window

### ISSUE THREAD

**Issue by aaronjensen** [BrowserSync/browser-sync#449]
I don't know exactly what is causing it, but about 50-70% of the time when I click on something while running browsersync, another click will come through on the same element about a second later. The click is coming from browsersync. I'm on 2.0.1, the clicks handler is an angular ng-click directive.

**Comment by shinnn** [comment]
@aaronjensen Could you create a small repository that can reproduce the error?

**Comment by aaronjensen** [comment]
Hm, I potentially could have when I wrote this, but I'm not on that project anymore and I don't remember exactly what caused it... sorry :/

**Comment by shinnn** [comment]
OK, closing this for now.

Thanks for reporting, @aaronjensen.

**Comment by Reklino** [comment]
Hm... I'm having this issue in an Angular 1.4 project. Any element using the 'ng-click' directive will fire randomly a few times a few seconds after I'm done clicking. It only happens when I click rapidly on the element. And it does NOT happen when I use 'ng-mouseup' instead. No other browsers or devices are up.

**Comment by shakyShane** [comment]
I've also noticed this recently...

**Comment by eritie** [comment]
Same here. triggerClick function is fired whenever you click more than once on some element. 
There is about 1s delay. I could only seem to reproduce it whenever on a page with a "window.location.pathname".
