### ISSUE TITLE
Breaking on HTML without body tag

### ISSUE THREAD

**Issue by zanona** [BrowserSync/browser-sync#496]
Unfortunately when a document has no `<body>` tag defined, browser-sync does not inject socket.io script and cannot work properly.

_Reminding here that not declaring a `body` on a html document is a perfectly valid approach_ :+1:

**Comment by shakyShane** [comment]
whilst it may be a

> perfectly valid approach

... we need *something* to match in order to confirm that it's HTML that we are modifying.

I know, this doesn't work for everyone, so now you can use [snippetOptions](http://www.browsersync.io/docs/options/#option-snippetOptions)

for example, to always place the snippet at the end of the file, you could do 

```js
snippetOptions: {
    // Provide a custom Regex for inserting the snippet.
    rule: {
        match: /$/,
        fn: function (snippet, match) {
            return snippet;
        }
    }
}
```

**Comment by zanona** [comment]
Brilliant! that feature is great! thanks man

**Comment by shakyShane** [comment]
@zanona no problem :)
