### ISSUE TITLE
Gulp - Error: cannot find module 'immutable'

### ISSUE THREAD

**Issue by thisisbrianhan** [BrowserSync/browser-sync#502]
# The Problem
I'm currently using browser-sync as a gulp dev-dependency for an express.js app.
Everything seems to work fine in a local version of this app but when I: 

- `git clone` the [repo](https://github.com/thisisbrianhan/brianhan.io)
- `npm install` 
- `npm start` or `nodemon ./bin/www`
- `gulp`

Running gulp will give me an error that looks related to `browser-sync` and `immutable`. 
Here's a truncated error (full errors near the end of the issue):
```
throw err;
      ^
Error: Cannot find module 'immutable'
...
(truncated for length)
...
```
When I look at the output from install browser-sync by itself, I can see that `immutable` is installing successfully:

```
$ npm install browser-sync --save-dev
```
```
...
CXX(target)
Release/obj.target/bufferutil/src/bufferutil.o
browser-sync@2.2.2 node_modules/browser-sync
...
├── immutable@3.6.3
...
```
# Attempted Solutions

- I've tried deleting my `node_modules` and re-installing all dependencies with `npm install` but the error still persists.

- In `package.json`, tried removing `^` and `~` from dependencies to lock-in versions for npm modules

- (Probably unnecessary but) Rebuilt the app from scratch to see if the error would still persist, and it does. Here's [the repo where I rebuilt it from scratch](https://github.com/thisisbrianhan/brianhan-io-restart). 

# Full Console Output (errors, immutable-related)

## Running npm install for browser-sync

```
$ npm install browser-sync --save-dev
```
```
npm WARN package.json brianhan-io-restart@1.0.0 No repository field.

> ws@0.5.0 install /Users/brianhan/Dev/sites/brianhan-io-restart/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /Users/brianhan/Dev/sites/brianhan-io-restart/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
browser-sync@2.2.2 node_modules/browser-sync
├── async-each-series@0.1.1
├── emitter-steward@0.0.1
├── opn@1.0.1
├── dev-ip@1.0.1
├── immutable@3.6.3
├── ua-parser-js@0.7.3
├── browser-sync-client@1.0.2
├── portscanner@1.0.0 (async@0.1.15)
├── meow@3.1.0 (object-assign@2.0.0, minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.1)
├── foxy@10.0.2 (cookie@0.1.2, meow@2.1.0, http-proxy@1.8.1)
├── resp-modifier@2.0.1 (minimatch@2.0.1)
├── easy-extender@2.2.0 (lodash@2.4.1)
├── connect@3.3.4 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.1.2, finalhandler@0.3.3)
├── serve-index@1.6.2 (parseurl@1.3.0, batch@0.5.2, debug@2.1.2, http-errors@1.3.1, accepts@1.2.4, mime-types@2.0.9)
├── serve-static@1.9.1 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, send@0.12.1)
├── glob-watcher@0.0.8 (gaze@0.5.1)
├── eazy-logger@2.1.1 (tfunk@3.0.1, opt-merger@1.1.0)
├── localtunnel@1.5.0 (debug@0.7.4, optimist@0.3.4, request@2.11.4)
├── lodash@3.4.0
├── socket.io@1.3.5 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.1, socket.io-client@1.3.5)
└── browser-sync-ui@0.4.9 (connect-history-api-fallback@0.0.5, angular-touch@1.3.14, angular-sanitize@1.3.14, angular-route@1.3.14, angular@1.3.14, weinre@2.0.0-pre-I0Z7U9OV)
```

## When running gulp

```
$ gulp
```
```
throw err;
      ^
Error: Cannot find module 'immutable'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/Users/brianhan/Dev/sites/brianhan-io-restart/node_modules/browser-sync/lib/hooks.js:4:20)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
```

# [My Repo](https://github.com/thisisbrianhan/brianhan-io-restart)

- [gulpfile.js](https://github.com/thisisbrianhan/brianhan-io-restart/blob/master/gulpfile.js)
- [package.json](https://github.com/thisisbrianhan/brianhan-io-restart/blob/master/package.json)
- [node_modules/browser-sync](https://github.com/thisisbrianhan/brianhan-io-restart/tree/master/node_modules/browser-sync)

**Comment by paradox41** [comment]
Happening to me as well, same stack trace.

**Comment by cnc137** [comment]
I don't know if this will help, since I am running BrowserSync from the command line in Terminal instead of via Gulp, but this is what I needed to do to fix the "Cannot find module 'immutable'" error message on my system.

I needed to install the "immutable" Node.js module globally using the following command with the "-g" flag so I didn't get an error telling me it cannot find the module:

npm install -g immutable

I also installed BrowserSync by executing the following command to install it globally:

npm install -g browser-sync

I installed it globally for now, but may install it locally under each project in the future.

This is probably not related, but I also changed the ownership of Node.js files so when installing modules I don't have to use "sudo" everytime using the following command:

sudo chown -R `whoami` /usr/local/lib/node_modules

More details about this are available at http://mawaha.com/permission-fix-node-js/ and https://docs.npmjs.com/getting-started/fixing-npm-permissions

They tell you to change ownership of the full "/usr/local" directory in the npmjs.com documentation, but I didn't want to do that, so I used the command above following the mawaha.com guide.

Lastly, I read that you may need to add "/usr/local/lib/node_modules/:" to your $PATH variable in the .bash_profile or .profile files by editing it and adding the following line:

export PATH=/usr/local/lib/node_modules/:$PATH

I tried this when having problems, but ended up removing it, since installing immutable globally I think resolved the problem. My PATH statement now looks like the following in my .bash_profile file under my home directory in OS X:

export PATH=/usr/local/bin:/usr/local/git/bin:$PATH

I have the PATH set this way so I can use the Homebrew version of Ruby and latest version of Git to load instead of the ones that come with OS X.

I hope this helps, but once again I am not trying to use BrowserSync via Gulp, so none of the above may apply.


export PATH=/usr/local/bin:/usr/local/git/bin:/usr/local/lib/node_modules/:$PATH

**Comment by thewillhuang** [comment]
this same error is happening to me on this version, no problems in 2.2.1

**Comment by shakyShane** [comment]
npm rm browser-sync && npm install browser-sync

The problem was with the immutable lib, which is now fixed.

**Comment by thisisbrianhan** [comment]
thanks @shakyShane!

**Comment by jeffkole** [comment]
@shakyShane What was the problem with the Immutable lib?  I'm seeing a similar error in a continuous integration environment (not using Browser Sync), but my build works just fine locally.

**Comment by shakyShane** [comment]
The immutable lib published a broken version. You should reinstall to fix

**Comment by jeffkole** [comment]
I'm using Immutable 3.7.1.  Looks like you were on 3.6.3.  Is that right?

**Comment by shakyShane** [comment]
3.6.3 was the broken release, so we bumbed

**Comment by sonvisal** [comment]
I have problem with run node js 

Start at Fri Dec 04 2015
module.js:339
    throw err;
    ^

Error: Cannot find module 'http-sync'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/visal/Downloads/influenceurs/INFLUENCEURS/influenceur.js:4:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
