### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by pikeas** [BrowserSync/browser-sync#515]
BrowserSync takes 5-10 seconds on startup to verify that the specified port is free. The timeout for this check is set to 1000 ms in `lib/utils.js`, so I'm not sure why it's taking so long.

Happens in both server and proxy mode.

Here's where it gets a bit strange. If I enable debug logging, it's clear that the process is hung while verifying that port 3000 is open. So I add `cb(null, 3000)` to that function and rerun. Now it hangs while testing the internet connection. Add `online: true` to the config, and it now it hangs on finding a port for the UI!

This suggests that there's something strange with the way BrowserSync initializes networking, or how its networking interacts with the underlying host. I'm a bit stumped on how to troubleshoot further.

**Comment by shakyShane** [comment]
All BrowserSync can do is *attempt* to find a free port - it's a convenience feature that be guaranteed to work/be fast in 100% of cases.

Whatever is causing the slow-down for you can be fixed by simply providing the ports & online options.

```js
browserSync({
    port: 3000,
    ui: {
        port: 3001
    },
    online: true
})
```

I know that's not ideal/pretty - but without being able to replicate your environment, it's the best I can offer :)

**Comment by pikeas** [comment]
@shakyShane Turns out the problem is with my Gulp task. For some reason using a negation glob (for example, `['**/*.ext', '!**/*.ext.bak']` causes the slow BrowserSync start. Removing the negation results in a nearly instantaneous BS startup. Doesn't make any sense.
