### ISSUE TITLE
Navigation breaks when multiple tabs are open

### ISSUE THREAD

**Issue by marcvangend** [BrowserSync/browser-sync#522]
I'm running Gulp while doing front-end tasks to perform various tasks like compiling sass and run jshint. It also runs BrowserSync (2.3.1) in snippet mode, mainly to inject changed css and reload when templates have changed. On occasions I use the ghostMode feature to test multiple browsers at once.

Sometimes, when I open multiple tabs of my development site in my browser, it breaks navigation: I click a link in the page, but it only reloads the current page. Once I have closed all other tabs, it returns to its expected behavior.

I have tried to stop this problem using the BrowserSync options, for instance adding

```js
    ghostMode: {
      clicks: false,
      forms: false,
      scroll: false
    },
```
but without succes.

Am I doing something wrong? Is there a configuration option I missed? Or is this a bug?

**Comment by shakyShane** [comment]
Do you mean that clicking a link does not navigate to that page at al (as if browser sync blocked it)? 

Or do you just mean that other browsers do not follow?

**Comment by bdukes** [comment]
I'm using Firefox on Windows, and seeing that clicking on a link reload the page, rather than navigating.  Similarly, entering a URL into the address bar just reloads the same page, rather than navigating (seems related to #486); entering a URL into a new tab's address bar works fine.  If I click on a link in Firefox, Chrome will follow the link, but Firefox will just reload.  Likewise, if I click a link in Chrome, it follows the link fine, but Firefox reloads without navigating.  In Firefox, if I click the link again after the page starts reloading and "BrowserSync Disconnected" shows, then I can sometimes get it to navigate correctly.

**Comment by shakyShane** [comment]
try setting 

```
reloadOnRestart: false
```

**Comment by bdukes** [comment]
That does appear to have fixed my issue.  Thanks!

**Comment by marcvangend** [comment]
I'll try that next Monday, first thing. Thanks!

**Comment by marcvangend** [comment]
As far as I can see, that fixed it. Thanks!

**Comment by shakyShane** [comment]
yeah sorry about that @marcvangend  - I'm thinking having it set to `false` as the default now as this issue has arisen many times.

**Comment by marcvangend** [comment]
That's okay, I'm glad you were available to help.

For my understanding: What behavior is that setting supposed to control? When would someone want to set it to `true`?

**Comment by shakyShane** [comment]
@marcvangend When you restart BrowserSync from the command line, you may of changed properties or even changed files in your website - so when a reconnection happens, browsers are reloaded to create a fresh context
