### ISSUE TITLE
rewriteRules matching twice

### ISSUE THREAD

**Issue by MattDiMu** [BrowserSync/browser-sync#733]
When using browser-sync in proxy mode, I use a Regex like this to insert a local JS-File

```js
rewriteRules: [
  {
    match: /<\/body>/,
    fn: function (match) {
      return '<script src="http://localhost:3000/resources/somefile.js"></script></body>';
    }
  }

```

This seems to apply twice, however. The closing body tag from the replaced String is matched again and I get a HTML-Result like this:

```js
<script src="http://localhost:3000/resources/somefile.js"></script><script src="http://localhost:3000/resources/somefile.js"></script></body>
```

A workaround was replacing the closing body tag with a uppercase one (```</Body>```), so the regex only matches once and is therefore only inserted once, but I have no idea why this is necessary.

You have any ideas / is this a bug?

Regards
Matt

**Comment by shakyShane** [comment]
This is not documented yet, so my apologies for that - but basically there's a problem in the way that the string replacements work currently - they can apply to individual chunks sent by a server, but also be applied on the entire response.

This is deliberate and allows strings that may of been missed because of chunking to still be replaced, but it has the negative effect of exactly what you detailed above.

For now, the solution is to provide `once: true` in your rule. So (assuming you're running `2.8.0`) - your config can look like 

```js
rewriteRules: [
    {
        match: /<\/body>/,
        once: true,
        replace: '<script src="http://localhost:3000/resources/somefile.js"></script></body>'
    }
]
```

**Comment by shakyShane** [comment]
I do hope to improve this situation, or at least heavily document it :)

**Comment by shakyShane** [comment]
https://github.com/shakyShane/resp-modifier/blob/master/lib/utils.js#L4-L52

**Comment by MattDiMu** [comment]
@shakyShane Thx a lot for your rapid response and explanation!

**Comment by andrebautista** [comment]
Hi @MattDiMu I'm currently running into this issue with multiple rewrites since the website I'm proxying is 3rd party and it contains multiple <body> tags. I attempted to use 2.8.x versions however it seems like the configuration specs have changed. Is there any kind of release documentation on this or is it deprecated?

**Comment by MattDiMu** [comment]
@andrebautista Are you sure you're experiencing the same problem? Mine could be solved by adjusting the regex.
