### ISSUE TITLE
gulp scss with gulp-rev injection not working - proxy setup

### ISSUE THREAD

**Issue by Marcel-Robitaille** [BrowserSync/browser-sync#774]
Please do not disregard this issue as a failed attempt to set up browser-sync. I believe this is a bug.

I am using gulp-rev to cache-bust my compiled scss files. This means the css injections works only when I don't change anything in my css file. If I change anything, gulp-rev will give it a different name and browserSync won't know to inject it. Here is the scss task in my gulpfile:

````javascript
Object.keys(styles).forEach(function(key){
    gulp.task('css-' + key, function(){
        del.sync([
            './public/' + styles[key].dir +  manifest[key + '.css'],
            './public/' + styles[key].dir + '/maps/' + manifest[key + '.css'] + '.map'
        ]);
        return gulp.src('./source/' + styles[key].dir + key + '.scss')
            .pipe(plumber())
            .pipe(sourcemaps.init())
            .pipe(sass())
            .pipe(minifycss())
            .pipe(autoprefixer())
            .pipe(rev())
            .pipe(sourcemaps.write('maps/'))
            .pipe(tap(updateManifest))
            .pipe(gulp.dest('public/' + styles[key].dir))
            .pipe(gulpif(
                function(file){return path.extname(file.path) === '.css'},
                browsersync.stream({match: "**/*.css"})
            ));
    });
});
````

I don't think this will help but the guidelines say to add it: I am using Windows 7.

**Comment by shakyShane** [comment]
Thanks @Marcel-Robitaille for the excellent question. I can see why you think this is an 'issue' with Browsersync, but if you'll allow me to explain...

So, you have something like `<link rel="stylesheet" href="a.css" />` in your html file.

Then, you make a change to your `sass` files and a new `b.css` is sent down-stream. `Browsersync.stream()` sees this file passing through and issues the command to all connected devices 'Hey all, update `b.css` please, if you have it.'

How exactly is Browsersync supposed to know that `b.css` should replace the existing `a.css`? Answer: it cannot (currently). 

CSS injection currently works in a very simple, stateless way - upon receiving the 'update `b.css`' command, it only looks for existing `<link>` tags that have a href attribute containing `b.css`.

2 things to think about:

1. Why are you version-revving at all in development? Cache-breaking in this manner is unnecessary whilst you're actually developing your CSS - it should be a task that occurs in a separate task when you want to deploy. (also, surely version revving on every file save like this is just creating lots of css files in your `public` directory?)

2. This could actually be achieved with a very simple plugin ( I can advise on that, if you want), but I'm reluctant to add this feature to core for two reasons - I don't think this is a common work flow & I don't want to encourage it either (because of what I mentioned in number 1 above)

**Comment by Marcel-Robitaille** [comment]
Thanks for your comments. I admit, my workflow is far from perfect. I will try to fix it up a bit.

**Comment by mewdriller** [comment]
Would you mind elaborating on a bit of option 2 @shakyShane? I've got a very peculiar and usual situation in which I'm proxy'ing in front of another server that is doing the fingerprinting. So I've got an asset coming through named something like `site.css` and it's getting changed to something like `site-<hash>.css`.

I was hoping there was an option in the call to `browserSync.stream()` to pass a glob for the match instead of using the exact name coming through the stream. Any thoughts?

**Comment by mewdriller** [comment]
@shakyShane After digging through the source a bit more, it looks like the path I was considering would require a change to the logic in [`sync.getMatches`](https://github.com/BrowserSync/browser-sync-client/blob/318092287f812837f71828ca8f2431ed04b40b2d/lib/code-sync.js#L275) on the client-side to match via glob rather than strict `indexOf` checks.

If was thinking something like:
```
sync.getMatches = function (elems, url, attr) {

    if (url[0] === "*") {
        return elems;
    }

    var matches = [];
    var matcher = new RegExp(url);

    for (var i = 0, len = elems.length; i < len; i += 1) {
        if (matcher.test(elems[i][attr])) {
            matches.push(elems[i]);
        }
    }

    return matches;
};
```
