### ISSUE TITLE
Refresh only changed pages

### ISSUE THREAD

**Issue by dimitarkolev** [BrowserSync/browser-sync#795]
I have very basic setup
```shell
browser-sync start --files "*.html" --server
```
May be I am missing something, but when I open index.html in the browser and edit services.html on the server index.html is reloaded in the browser. Is this expected behaviour or I am doing something wrong?

**Comment by shakyShane** [comment]
currently, this is expected behaviour.

The lack of mapping between the file you edited & the current path in the browser is deliberate - think of a setup where you're using partials for example. If you were to edit `partial.html`, but the browser is currently at `index.html` then you'd get *no* reloading...

This being said, in a future release there *will* be an option to maintain an exact mapping as you desire. But I'm afraid you'll have to wait a short while for that :)

**Comment by ericmorandcross** [comment]
@shakyShane is this feature (*an option to maintain an exact mapping as you desire*) still on the roadmap?
