### ISSUE TITLE
ci: drop iojs?

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/browser-sync#805]

**Comment by shinnn** [comment]
After node 4.0 is released, yes, we don't need to test with io.js.

But, if the reason to drop it is only because you don't want to see the red badge, it's just a postponent of the problem.

io.js 3.x is alpha version of the next stable node, 4.0. If a module is not compatible with io.js, it also not compatible with the latest node.

**Comment by shakyShane** [comment]
It literally harms the project when the badges are not green, was my main point there

**Comment by shinnn** [comment]
> I think it's wise to test only on platforms that have the greatest amount of users

https://github.com/nodejs/node/issues/2522

Node 4.0 will be released soon and a lot of developers will switch to the new stable version from 0.x. If we don't fix the problem with io.js, that means browser-sync won't work with the latest node that is going to get a large user-base. It's better to fix the problem actually, instead of makeshift.

**Comment by shakyShane** [comment]
ok agreed

**Comment by shinnn** [comment]
OK, [Node v4.0.0 has been released](https://github.com/nodejs/node/blob/380a3d89c3f04197a676b8037e3112404923670c/CHANGELOG.md#2015-09-08-version-400-stable-rvagg) and Browsersync passed the test using v4.0.0. https://travis-ci.org/BrowserSync/browser-sync/jobs/79350666#L85

We can drop io.js test now.

**Comment by shakyShane** [comment]
windows?

**Comment by shakyShane** [comment]
btw @shinnn have you tried v4 yet? Can't believe it ships with up-to-date V8

**Comment by shinnn** [comment]
Windows test still uses io.js v2.0 and we can't see if it passes the test using Node v4.0.0 for now. Anyway we should update appveyor.yml too.

**Comment by shinnn** [comment]
> have you tried v4 yet?

Yes. I'm developing my website project with gulp, Browsersync and Nodev4.0.0. it works fine.

> Can't believe it ships with up-to-date V8

```
$ node -v
> v4.0.0
$ node -e "const fn = () => 1; console.log(fn())"
> 1
```

**Comment by shinnn** [comment]
@shakyShane Do you still want me to keep this policy? https://github.com/BrowserSync/browser-sync/commit/c31c3d1cb58da1bd6b874fbf339ba34440a04043#commitcomment-11038791

> I think we need to move to a branch + pull request model for master.

I can directly update CI settings soon, but I can also create a pull request to try to realize branch + pull request model.

**Comment by shakyShane** [comment]
No just work straight on master for the moment until we have a process documented :)

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/commit/2518575ddc43d69b8cdd962a30b53ac369aaf7df
