### ISSUE TITLE
problem running for Protractor tests

### ISSUE THREAD

**Issue by yoorek** [BrowserSync/browser-sync#808]
my Protractor tests are running perfectly with 'grunt-connect' but when i try to test same app under browser-sync I get:

'Failed: Angular could not be found on the page http://localhost:3000/lib/iqsec/ui/src/index.html#/?redirect_url=http://localhost:3000/dist/index.html : angular never provided resumeBootstrap'

**Comment by shakyShane** [comment]
This sounds like a simple error in your configuration.

Please provide an example project that highlights this bug - if you do that we may be able to point you in the correct direction

**Comment by benjaminkitt** [comment]
I've been spending the day troubleshooting this and here's the solution:

You need to add ``scrollRestoreTechnique: 'cookie'` to your browsersync config.

Protractor uses an Angular feature called [Deferred Bootstrap](https://code.angularjs.org/1.4.7/docs/guide/bootstrap) that uses `window.name` and conflicts with BrowserSync. From the AngularJS Docs:

>This feature enables tools like Batarang and test runners to hook into angular's bootstrap process and sneak in more modules into the DI registry which can replace or augment DI services for the purpose of instrumentation or mocking out heavy dependencies.

>If window.name contains prefix NG_DEFER_BOOTSTRAP! when angular.bootstrap is called, the bootstrap process will be paused until angular.resumeBootstrap() is called.

If Browsersync overwrites that `window.name` value before it gets caught by Angular, Angular will not defer its Bootstrap and Protractor will subsequently not be able to find the `resumeBootstrap` function because it won't exist.

Telling Browsersync to use a cookie instead of window.name resolves the conflict.

**Comment by shakyShane** [comment]
@benjaminkitt Thank you very much for providing this info.

In addition to this issue, the upcoming Browsersync 3 intends to use `window.name` even more, so we really need to do this in a smarter way, I will investigate how protractor/angular are working with it.

**Comment by shakyShane** [comment]
https://github.com/angular/angular.js/blob/master/src/Angular.js#L1600-L1622

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync-client/blob/master/lib/code-sync.js#L96

This was me thinking 'surely no-one else uses `window.name`

```js
$window.name = "";
```

:(

**Comment by shakyShane** [comment]
fixed in browser-sync@2.9.11

**Comment by jkatsnelson** [comment]
@benjaminkitt you saved my life. you are a gentlemen and a scholar.
