### ISSUE TITLE
If you use the "content-encoding:gzip" header, BrowserSync will not be able to inject its script to the body tag, so will not reload the browser

### ISSUE THREAD

**Issue by manuel-di-iorio** [BrowserSync/browser-sync#904]
Hi, I think to have discovered a little bug.
For my server, I set the Content-Encoding gzip to the response.

To correctly read the page with BrowserSync, I added a middleware as your example:

```js
	gulp.task('browserSync', function() {
		browserSync.init({
			proxy: "localhost",
			middleware: function(req, res, next) {
				res.setHeader("Content-Encoding", "gzip");
				next();
			}
		});
	});
```

Unfortunately Browsersync will not inject its script to the body tag (that exists in the html page).
In fact, if I disable the server gzip encoding, all works.

It's not a great bug, I can simply disable the encoding in development environment as workaround but obviously I want to report it (if not already reported).
Cheers!

**Comment by shakyShane** [comment]
The proxy does try to disable all gzipping so that the script injection can work as expected... I guess in some cases it fails.

I'm actually happy with this situation and don't consider this a bug, (given that Browsersync is a development-only tool).

Thanks for your input :) If this issue cropped up again in the future I may add some info to the docs :)

**Comment by manuel-di-iorio** [comment]
A solution could be to detect the header and automatically decode the page, before the script injection

**Comment by manuel-di-iorio** [comment]
I update this to say that gzip is working now with BrowserSync, don't know if it was only a mine configuration mistake or this was resolved in a new version, however it works, even with pre-gzipped assets, thanks!
