### ISSUE TITLE
Video in home page cannot be loaded

### ISSUE THREAD

**Issue by ahmehri** [BrowserSync/browser-sync#949]
In the home page of the website https://www.browsersync.io/. The video doesn't get loaded when playing it.

**Comment by impressivewebs** [comment]
FYI - this is happening because a file associated with the video is on a non-HTTPS URL. In Chrome, you'll see a message that looks like this:

https://i.gyazo.com/ddef15625dd71a1a7bb61442f791a94e.png

Which you'll see if you click the little gray shield icon on the right side of the address bar. You can allow the script, then the video will play, but then the green https indicator in the address bar will turn red, indicating a mixed content warning.

**Comment by shakyShane** [comment]
This has been removed for the time being (it was down to Quickcasts not allowing https embeds). It needs a new video anyway so this will encourage me to get it done sooner :)
