### ISSUE TITLE
In proxy mode urls without protocol do not work 

### ISSUE THREAD

**Issue by manueleone** [BrowserSync/browser-sync#965]
Hi,
first of all, thank you for your awesome job!
 
I noticed a strange behavior that caused BrowserSync not to work for me (I'm using it with gulp):
in my app, I was using absolute urls starting with "//" instead of "http://" (e.g. "//mysite.dev/assets/css/main.min.css") but the browser was disconnecting, switching from BrowserSync server url to proxy url.

I don't know if it can be considered a "bug", but I hope it can help someone with the same configuration.
Bye :)

**Comment by shakyShane** [comment]
using `//` is now considered an anti-pattern, can you not simply use relative urls? Or use the full full complete with either `http` or `https`

We use `//` with Browsersync just to help the proxy mode work in more situations and because its a development only tool, we don't mind that it's an anti-pattern.

Either way, can you copy/paste some sample markup showing the problem? (before Browsersync has done any rewriting) :)

**Comment by lkraav** [comment]
> using // is now considered an anti-pattern, can you not simply use relative urls? Or use the full full complete with either http or https

Source for this information?

**Comment by marvinhagemeister** [comment]
Because it leads to mixed content errors when using ssl: http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by manueleone** [comment]
Hi,
yes I can, I already changed it. 
I opened the issue only because it took me some time to figure out (maybe it was written some where, but I didn't find it)!

Thanks anyway ;)
